"""create_all_tables

Revision ID: 21c2a0d6048e
Revises: 
Create Date: 2026-06-13 13:20:01.191186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21c2a0d6048e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incident_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_types_id'), 'incident_types', ['id'], unique=False)
    op.create_index(op.f('ix_incident_types_name'), 'incident_types', ['name'], unique=True)
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_locations_id'), 'locations', ['id'], unique=False)
    op.create_index(op.f('ix_locations_name'), 'locations', ['name'], unique=True)
    op.create_table('routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_routes_code'), 'routes', ['code'], unique=True)
    op.create_index(op.f('ix_routes_id'), 'routes', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_number', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicles_id'), 'vehicles', ['id'], unique=False)
    op.create_index(op.f('ix_vehicles_vehicle_number'), 'vehicles', ['vehicle_number'], unique=True)
    op.create_table('delay_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('time', sa.Time(), nullable=True),
    sa.Column('day', sa.String(), nullable=True),
    sa.Column('min_delay', sa.Integer(), nullable=True),
    sa.Column('min_gap', sa.Integer(), nullable=True),
    sa.Column('direction', sa.String(), nullable=True),
    sa.Column('route_id', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('incident_type_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['incident_type_id'], ['incident_types.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delay_records_id'), 'delay_records', ['id'], unique=False)
    op.create_index(op.f('ix_delay_records_incident_type_id'), 'delay_records', ['incident_type_id'], unique=False)
    op.create_index(op.f('ix_delay_records_location_id'), 'delay_records', ['location_id'], unique=False)
    op.create_index(op.f('ix_delay_records_report_date'), 'delay_records', ['report_date'], unique=False)
    op.create_index(op.f('ix_delay_records_route_id'), 'delay_records', ['route_id'], unique=False)
    op.create_index(op.f('ix_delay_records_vehicle_id'), 'delay_records', ['vehicle_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_delay_records_vehicle_id'), table_name='delay_records')
    op.drop_index(op.f('ix_delay_records_route_id'), table_name='delay_records')
    op.drop_index(op.f('ix_delay_records_report_date'), table_name='delay_records')
    op.drop_index(op.f('ix_delay_records_location_id'), table_name='delay_records')
    op.drop_index(op.f('ix_delay_records_incident_type_id'), table_name='delay_records')
    op.drop_index(op.f('ix_delay_records_id'), table_name='delay_records')
    op.drop_table('delay_records')
    op.drop_index(op.f('ix_vehicles_vehicle_number'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_id'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_routes_id'), table_name='routes')
    op.drop_index(op.f('ix_routes_code'), table_name='routes')
    op.drop_table('routes')
    op.drop_index(op.f('ix_locations_name'), table_name='locations')
    op.drop_index(op.f('ix_locations_id'), table_name='locations')
    op.drop_table('locations')
    op.drop_index(op.f('ix_incident_types_name'), table_name='incident_types')
    op.drop_index(op.f('ix_incident_types_id'), table_name='incident_types')
    op.drop_table('incident_types')
    # ### end Alembic commands ###
