"""add_weather_records

Revision ID: 84aa1d1b483c
Revises: bc8ec9f79c37
Create Date: 2026-06-21 15:28:03.085371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84aa1d1b483c'
down_revision: Union[str, Sequence[str], None] = 'bc8ec9f79c37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weather_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('temp_max', sa.Float(), nullable=True),
    sa.Column('temp_min', sa.Float(), nullable=True),
    sa.Column('precipitation', sa.Float(), nullable=True),
    sa.Column('snowfall', sa.Float(), nullable=True),
    sa.Column('weather_code', sa.Integer(), nullable=True),
    sa.Column('weather_desc', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weather_records_date'), 'weather_records', ['date'], unique=True)
    op.create_index(op.f('ix_weather_records_id'), 'weather_records', ['id'], unique=False)
    op.add_column('delay_records', sa.Column('weather_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_delay_records_weather_id'), 'delay_records', ['weather_id'], unique=False)
    op.create_foreign_key(None, 'delay_records', 'weather_records', ['weather_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'delay_records', type_='foreignkey')
    op.drop_index(op.f('ix_delay_records_weather_id'), table_name='delay_records')
    op.drop_column('delay_records', 'weather_id')
    op.drop_index(op.f('ix_weather_records_id'), table_name='weather_records')
    op.drop_index(op.f('ix_weather_records_date'), table_name='weather_records')
    op.drop_table('weather_records')
    # ### end Alembic commands ###
