"""add_delay_record_enrichment_fields

Revision ID: 9f62d2c2480b
Revises: b2c3d4e5f6g7
Create Date: 2026-06-13 15:59:18.072049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f62d2c2480b'
down_revision: Union[str, Sequence[str], None] = 'b2c3d4e5f6g7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('delay_records', sa.Column('delay_hours', sa.Float(), nullable=True))
    op.add_column('delay_records', sa.Column('delay_severity', sa.String(), nullable=True))
    op.add_column('delay_records', sa.Column('time_slot', sa.String(), nullable=True))
    op.add_column('delay_records', sa.Column('season', sa.String(), nullable=True))
    op.add_column('delay_records', sa.Column('is_weekend', sa.Boolean(), nullable=True))
    op.add_column('delay_records', sa.Column('normalized_direction', sa.String(), nullable=True))
    op.add_column('delay_records', sa.Column('year', sa.Integer(), nullable=True))
    op.add_column('delay_records', sa.Column('month', sa.Integer(), nullable=True))
    op.add_column('delay_records', sa.Column('week', sa.Integer(), nullable=True))
    op.add_column('delay_records', sa.Column('quarter', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_delay_records_delay_severity'), 'delay_records', ['delay_severity'], unique=False)
    op.create_index(op.f('ix_delay_records_month'), 'delay_records', ['month'], unique=False)
    op.create_index(op.f('ix_delay_records_normalized_direction'), 'delay_records', ['normalized_direction'], unique=False)
    op.create_index(op.f('ix_delay_records_season'), 'delay_records', ['season'], unique=False)
    op.create_index(op.f('ix_delay_records_time_slot'), 'delay_records', ['time_slot'], unique=False)
    op.create_index(op.f('ix_delay_records_year'), 'delay_records', ['year'], unique=False)
    op.drop_constraint(op.f('location_coordinates_location_id_key'), 'location_coordinates', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('location_coordinates_location_id_key'), 'location_coordinates', ['location_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_delay_records_year'), table_name='delay_records')
    op.drop_index(op.f('ix_delay_records_time_slot'), table_name='delay_records')
    op.drop_index(op.f('ix_delay_records_season'), table_name='delay_records')
    op.drop_index(op.f('ix_delay_records_normalized_direction'), table_name='delay_records')
    op.drop_index(op.f('ix_delay_records_month'), table_name='delay_records')
    op.drop_index(op.f('ix_delay_records_delay_severity'), table_name='delay_records')
    op.drop_column('delay_records', 'quarter')
    op.drop_column('delay_records', 'week')
    op.drop_column('delay_records', 'month')
    op.drop_column('delay_records', 'year')
    op.drop_column('delay_records', 'normalized_direction')
    op.drop_column('delay_records', 'is_weekend')
    op.drop_column('delay_records', 'season')
    op.drop_column('delay_records', 'time_slot')
    op.drop_column('delay_records', 'delay_severity')
    op.drop_column('delay_records', 'delay_hours')
    # ### end Alembic commands ###
