"""initial

Revision ID: bc8ec9f79c37
Revises: 
Create Date: 2026-06-21 15:20:51.187656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc8ec9f79c37'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incident_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_categories_id'), 'incident_categories', ['id'], unique=False)
    op.create_index(op.f('ix_incident_categories_name'), 'incident_categories', ['name'], unique=True)
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_locations_id'), 'locations', ['id'], unique=False)
    op.create_index(op.f('ix_locations_name'), 'locations', ['name'], unique=True)
    op.create_table('routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_routes_code'), 'routes', ['code'], unique=True)
    op.create_index(op.f('ix_routes_id'), 'routes', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_number', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicles_id'), 'vehicles', ['id'], unique=False)
    op.create_index(op.f('ix_vehicles_vehicle_number'), 'vehicles', ['vehicle_number'], unique=True)
    op.create_table('incident_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['incident_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_types_category_id'), 'incident_types', ['category_id'], unique=False)
    op.create_index(op.f('ix_incident_types_id'), 'incident_types', ['id'], unique=False)
    op.create_index(op.f('ix_incident_types_name'), 'incident_types', ['name'], unique=True)
    op.create_table('location_coordinates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('full_address', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_location_coordinates_id'), 'location_coordinates', ['id'], unique=False)
    op.create_index(op.f('ix_location_coordinates_location_id'), 'location_coordinates', ['location_id'], unique=True)
    op.create_table('delay_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('time', sa.Time(), nullable=True),
    sa.Column('day', sa.String(), nullable=True),
    sa.Column('min_delay', sa.Integer(), nullable=True),
    sa.Column('min_gap', sa.Integer(), nullable=True),
    sa.Column('direction', sa.String(), nullable=True),
    sa.Column('route_id', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('incident_type_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('delay_hours', sa.Float(), nullable=True),
    sa.Column('delay_severity', sa.String(), nullable=True),
    sa.Column('time_slot', sa.String(), nullable=True),
    sa.Column('season', sa.String(), nullable=True),
    sa.Column('is_weekend', sa.Boolean(), nullable=True),
    sa.Column('normalized_direction', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('month', sa.Integer(), nullable=True),
    sa.Column('week', sa.Integer(), nullable=True),
    sa.Column('quarter', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['incident_type_id'], ['incident_types.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_delay_records_day', 'delay_records', ['day'], unique=False)
    op.create_index(op.f('ix_delay_records_delay_severity'), 'delay_records', ['delay_severity'], unique=False)
    op.create_index(op.f('ix_delay_records_id'), 'delay_records', ['id'], unique=False)
    op.create_index(op.f('ix_delay_records_incident_type_id'), 'delay_records', ['incident_type_id'], unique=False)
    op.create_index('ix_delay_records_incident_type_id_min_delay', 'delay_records', ['incident_type_id', 'min_delay'], unique=False)
    op.create_index(op.f('ix_delay_records_location_id'), 'delay_records', ['location_id'], unique=False)
    op.create_index('ix_delay_records_location_id_min_delay', 'delay_records', ['location_id', 'min_delay'], unique=False)
    op.create_index('ix_delay_records_min_delay', 'delay_records', ['min_delay'], unique=False)
    op.create_index(op.f('ix_delay_records_month'), 'delay_records', ['month'], unique=False)
    op.create_index(op.f('ix_delay_records_normalized_direction'), 'delay_records', ['normalized_direction'], unique=False)
    op.create_index(op.f('ix_delay_records_report_date'), 'delay_records', ['report_date'], unique=False)
    op.create_index(op.f('ix_delay_records_route_id'), 'delay_records', ['route_id'], unique=False)
    op.create_index('ix_delay_records_route_id_location_id', 'delay_records', ['route_id', 'location_id'], unique=False)
    op.create_index('ix_delay_records_route_id_min_delay', 'delay_records', ['route_id', 'min_delay'], unique=False)
    op.create_index(op.f('ix_delay_records_season'), 'delay_records', ['season'], unique=False)
    op.create_index(op.f('ix_delay_records_time_slot'), 'delay_records', ['time_slot'], unique=False)
    op.create_index(op.f('ix_delay_records_vehicle_id'), 'delay_records', ['vehicle_id'], unique=False)
    op.create_index('ix_delay_records_vehicle_id_min_delay', 'delay_records', ['vehicle_id', 'min_delay'], unique=False)
    op.create_index(op.f('ix_delay_records_year'), 'delay_records', ['year'], unique=False)
    op.create_index('ix_delay_records_year_month', 'delay_records', ['year', 'month'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_delay_records_year_month', table_name='delay_records')
    op.drop_index(op.f('ix_delay_records_year'), table_name='delay_records')
    op.drop_index('ix_delay_records_vehicle_id_min_delay', table_name='delay_records')
    op.drop_index(op.f('ix_delay_records_vehicle_id'), table_name='delay_records')
    op.drop_index(op.f('ix_delay_records_time_slot'), table_name='delay_records')
    op.drop_index(op.f('ix_delay_records_season'), table_name='delay_records')
    op.drop_index('ix_delay_records_route_id_min_delay', table_name='delay_records')
    op.drop_index('ix_delay_records_route_id_location_id', table_name='delay_records')
    op.drop_index(op.f('ix_delay_records_route_id'), table_name='delay_records')
    op.drop_index(op.f('ix_delay_records_report_date'), table_name='delay_records')
    op.drop_index(op.f('ix_delay_records_normalized_direction'), table_name='delay_records')
    op.drop_index(op.f('ix_delay_records_month'), table_name='delay_records')
    op.drop_index('ix_delay_records_min_delay', table_name='delay_records')
    op.drop_index('ix_delay_records_location_id_min_delay', table_name='delay_records')
    op.drop_index(op.f('ix_delay_records_location_id'), table_name='delay_records')
    op.drop_index('ix_delay_records_incident_type_id_min_delay', table_name='delay_records')
    op.drop_index(op.f('ix_delay_records_incident_type_id'), table_name='delay_records')
    op.drop_index(op.f('ix_delay_records_id'), table_name='delay_records')
    op.drop_index(op.f('ix_delay_records_delay_severity'), table_name='delay_records')
    op.drop_index('ix_delay_records_day', table_name='delay_records')
    op.drop_table('delay_records')
    op.drop_index(op.f('ix_location_coordinates_location_id'), table_name='location_coordinates')
    op.drop_index(op.f('ix_location_coordinates_id'), table_name='location_coordinates')
    op.drop_table('location_coordinates')
    op.drop_index(op.f('ix_incident_types_name'), table_name='incident_types')
    op.drop_index(op.f('ix_incident_types_id'), table_name='incident_types')
    op.drop_index(op.f('ix_incident_types_category_id'), table_name='incident_types')
    op.drop_table('incident_types')
    op.drop_index(op.f('ix_vehicles_vehicle_number'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_id'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_routes_id'), table_name='routes')
    op.drop_index(op.f('ix_routes_code'), table_name='routes')
    op.drop_table('routes')
    op.drop_index(op.f('ix_locations_name'), table_name='locations')
    op.drop_index(op.f('ix_locations_id'), table_name='locations')
    op.drop_table('locations')
    op.drop_index(op.f('ix_incident_categories_name'), table_name='incident_categories')
    op.drop_index(op.f('ix_incident_categories_id'), table_name='incident_categories')
    op.drop_table('incident_categories')
    # ### end Alembic commands ###
